# yaml(Yet Another Markup Language) 另一种标记语言
# yaml树形结构层次清晰,不用写大量重复的key,可读性好,输入关键字有完整提示,冒号后面必须有空格
# 配置项官方文档
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.core
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.web
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data

# server配置(org.springframework.boot.autoconfigure.web.ServerProperties)
server:
  # 端口号
  port: 8080
  # 项目根路径
  servlet:
    context-path: /

# spring配置
spring:
  # spring.web配置(org.springframework.boot.autoconfigure.web.WebProperties)
  web:
    # 静态资源
    resources:
      # 静态资源默认放在static目录,且请求路径不需要加目录名称localhost:8080/a.html
      # 那我就想放到webapp目录下呢,手动修改配置参数即可,此时默认的静态资源目录就无法访问了
      static-locations: classpath:/webapp
      # 开启静态资源映射规则
      add-mappings: true
      # 缓存配置
      cache:
        cachecontrol:
          # 缓存周期(秒)
          max-age: 3600
          # 共享缓存
          cache-public: true
        # 和服务器比对资源的最后一次修改时间,如果没变就直接使用本地缓存,节省服务器资源,F12响应状态码304表示使用了缓存
        use-last-modified: true

  # spring.mvc配置(org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties)
  mvc:
    # 路径匹配规则：默认是新版策略path_pattern_parser,可以切换成老版策略ant_path_matcher
    pathmatch:
      matching-strategy: ant_path_matcher
    # 内容协商
    contentnegotiation:
      # 基于请求参数的内容协商,默认关闭
      favor-parameter: true
      # 参数名默认format,也可以手动指定,比如改成type
      parameter-name: format
      # 增加一种新的媒体类型
      media-types:
        yaml: text/yaml

# 日志相关配置(推荐使用logback-spring.xml)
logging:
  # 时间格式
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  # 日志分组
  group:
    g01: com.okccc.controller, com.okccc.service
    g02: com.okccc.mapper
  # 日志级别
  level:
    root: info
    web: info
    sql: debug
    g01: info
    g02: debug
  # 输出到文件
  file:
    name: /tmp/app.log
  # 文件归档与滚动和切割
  logback:
    rollingpolicy:
      file-name-pattern: app.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 1MB